### ISSUE TITLE
Audio link block missing

### ISSUE THREAD

**Issue by ghost** [ZarTek-Creole/TCL-DictionaryAPI#1]
<user> .define kiss
<Bot> DictionaryAPI> "kiss" ({text kjs audio //ssl.gstatic.com/dictionary/static/sounds/20200429/kiss--_gb_2.mp3}) - verb > (plant a kiss on, brush one's lips against, blow a kiss to, air-kiss, peck, give a peck to, give a smacker to, smooch, canoodle, neck, pet, kiss and cuddle, bill and coo, snog, buss, spoon, osculate) 1  > touch or caress with the lips as a sign of love, sexual desire, or greeting. > "he kissed her on the lips"
<Bot> DictionaryAPI> "kiss" ({text kjs audio //ssl.gstatic.com/dictionary/static/sounds/20200429/kiss--_gb_2.mp3}) - verb > (plant a kiss on, brush one's lips against, blow a kiss to, air-kiss, peck, give a peck to, give a smacker to, smooch, canoodle, neck, pet, kiss and cuddle, bill and coo, snog, buss, spoon, osculate) 2  > (of a ball) lightly touch (another ball) in passing. > "he kissed her on the lips"

<user> .define single
<BOT> DictionaryAPI> "single" ({text ÈsjKa(Y)l audio //ssl.gstatic.com/dictionary/static/sounds/20200429/single--_gb_1.mp3}) - adjective > (one, one only, sole, lone, solitary, isolated, by itself, unique, exclusive, unaccompanied, by oneself, alone, solo, odd) 1  > only one; not one of several. > "a single red rose"
<BOT> DictionaryAPI> "single" ({text ÈsjKa(Y)l audio //ssl.gstatic.com/dictionary/static/sounds/20200429/single--_gb_1.mp3}) - adjective > (unmarried, unattached, free, available, eligible, young, and single, footloose and fancy free, unwed, unwedded, wifeless, husbandless, spouseless, partnerless, a bachelor, on the shelf, a spinster, sole) 2  > unmarried or not involved in a stable sexual relationship. > "a single mother"

----->>>>>      **can we  show like this..**

<user>.define kiss
<Bot> DictionaryAPI> "kiss"  - verb > (plant a kiss on, brush one's lips against, blow a kiss to, air-kiss, peck, give a peck to, give a smacker to, smooch, canoodle, neck, pet, kiss and cuddle, bill and coo, snog, buss, spoon, osculate) 2  > (of a ball) lightly touch (another ball) in passing. > "he kissed her on the lips"

<user>.define single
<BOT> DictionaryAPI> "single" - adjective > (unmarried, unattached, free, available, eligible, young, and single, footloose and fancy free, unwed, unwedded, wifeless, husbandless, spouseless, partnerless, a bachelor, on the shelf, a spinster, sole) 2  > unmarried or not involved in a stable sexual relationship. > "a single mother"

<BOT> DictionaryAPI> "single" - adjective > (unmarried, unattached, free, available, eligible, young, and single, footloose and fancy free, unwed, unwedded, wifeless, husbandless, spouseless, partnerless, a bachelor, on the shelf, a spinster, sole) 2  > unmarried or not involved in a stable sexual relationship. > "a single mother"

**Comment by ZarTek-Creole** [comment]
`({text kjs audio //ssl.gstatic.com/dictionary/static/sounds/20200429/kiss--_gb_2.mp3}) `
This is a bug, the script does not recognize the AUDIO block when it is present. This must be created. This will allow to display it or not, at the desire of the user of the script.

**Comment by ghost** [comment]
oh ok.. well then.. i think now it is working perfect.. :) ...
